export enum Message {
    AFFICHER_CONFIGURATEUR = 0,
    AFFICHER_SEANCE = 1,
    SELECTION_EXERCICE = 2,
    MODIFIER_EXERCICE = 3,
    RESET_CONFIGURATEUR = 4,
    COMMENCER_SEANCE = 5,
    RESET_CHRONO = 6,
    ENVOYER_ID_EXO = 7,
}